### ISSUE TITLE
what it a csc.exe?

### ISSUE THREAD

**Issue by cn27529** [isdaviddong/KrajeeFileUploadExample#1]
nuget還原安裝後, 運作程序時出現
![image](https://user-images.githubusercontent.com/7908182/61192555-c2f4f380-a6e7-11e9-98bd-467900279777.png)

**Comment by isdaviddong** [comment]
FYI.
https://marcus116.blogspot.com/2018/11/net-web-api-bin-roslyn-cscexe.html
